version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
      args:
        - WITH_XDEBUG=${WITH_XDEBUG}
        - XDEBUG_TRIGGER_PROFILER=${XDEBUG_TRIGGER_PROFILER}
        - XDEBUG_PROFILER_DIR=${XDEBUG_PROFILER_DIR}
        - TIMEZONE=${TIMEZONE}
        - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
        - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
        - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker_tmp:/docker_tmp
    environment:
      - "DB_PORT=${DB_PORT}"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - "${APP_HOST_PORT}:80"

  # The Database
  database:
    image: mariadb:10.3.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "TIMEZONE=${TIMEZONE}"
    ports:
        - "${DB_HOST_PORT}:${DB_PORT}"

volumes:
  dbdata:
